//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_WF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMuon
    {
        public string MaPM { get; set; }
        public string MaCS { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual CuonSach CuonSach { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
