//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_WF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhap
    {
        public string MaPN { get; set; }
        public string MaTS { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual TuaSach TuaSach { get; set; }
    }
}
