//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_WF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyThuVienEntities : DbContext
    {
        public QuanLyThuVienEntities()
            : base("name=QuanLyThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietMuon> ChiTietMuons { get; set; }
        public virtual DbSet<ChiTietNhap> ChiTietNhaps { get; set; }
        public virtual DbSet<CuonSach> CuonSaches { get; set; }
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<GiaoVien> GiaoViens { get; set; }
        public virtual DbSet<KeSach> KeSaches { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PhieuMuon> PhieuMuons { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<ThuThu> ThuThus { get; set; }
        public virtual DbSet<TuaSach> TuaSaches { get; set; }
        public virtual DbSet<Viet> Viets { get; set; }
        public virtual DbSet<vw_ThongKeChuaMuon> vw_ThongKeChuaMuon { get; set; }
    
        public virtual int CapNhat_TS_V(string mats, string tents, Nullable<int> namxb, string theloai, string manxb, string make, Nullable<int> soluong, string matg, Nullable<int> sotrang)
        {
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var tentsParameter = tents != null ?
                new ObjectParameter("tents", tents) :
                new ObjectParameter("tents", typeof(string));
    
            var namxbParameter = namxb.HasValue ?
                new ObjectParameter("namxb", namxb) :
                new ObjectParameter("namxb", typeof(int));
    
            var theloaiParameter = theloai != null ?
                new ObjectParameter("theloai", theloai) :
                new ObjectParameter("theloai", typeof(string));
    
            var manxbParameter = manxb != null ?
                new ObjectParameter("manxb", manxb) :
                new ObjectParameter("manxb", typeof(string));
    
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var matgParameter = matg != null ?
                new ObjectParameter("matg", matg) :
                new ObjectParameter("matg", typeof(string));
    
            var sotrangParameter = sotrang.HasValue ?
                new ObjectParameter("sotrang", sotrang) :
                new ObjectParameter("sotrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhat_TS_V", matsParameter, tentsParameter, namxbParameter, theloaiParameter, manxbParameter, makeParameter, soluongParameter, matgParameter, sotrangParameter);
        }
    
        public virtual ObjectResult<Cbb_CS_Result> Cbb_CS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cbb_CS_Result>("Cbb_CS");
        }
    
        public virtual ObjectResult<Cbb_DG_Result> Cbb_DG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cbb_DG_Result>("Cbb_DG");
        }
    
        public virtual ObjectResult<Cbb_KeSach_Result> Cbb_KeSach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cbb_KeSach_Result>("Cbb_KeSach");
        }
    
        public virtual ObjectResult<Cbb_NCC_Result> Cbb_NCC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cbb_NCC_Result>("Cbb_NCC");
        }
    
        public virtual ObjectResult<Cbb_NXB_Result> Cbb_NXB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cbb_NXB_Result>("Cbb_NXB");
        }
    
        public virtual ObjectResult<Cbb_TacGia_Result> Cbb_TacGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cbb_TacGia_Result>("Cbb_TacGia");
        }
    
        public virtual ObjectResult<Cbb_TS_Result> Cbb_TS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cbb_TS_Result>("Cbb_TS");
        }
    
        public virtual ObjectResult<Cbb_TT_Result> Cbb_TT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cbb_TT_Result>("Cbb_TT");
        }
    
        public virtual ObjectResult<string> ChuaMuon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ChuaMuon");
        }
    
        public virtual ObjectResult<DaMuon_Result> DaMuon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DaMuon_Result>("DaMuon");
        }
    
        public virtual int Delete_CS(string macs)
        {
            var macsParameter = macs != null ?
                new ObjectParameter("macs", macs) :
                new ObjectParameter("macs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_CS", macsParameter);
        }
    
        public virtual int Delete_CTM(string mapm, string macs)
        {
            var mapmParameter = mapm != null ?
                new ObjectParameter("mapm", mapm) :
                new ObjectParameter("mapm", typeof(string));
    
            var macsParameter = macs != null ?
                new ObjectParameter("macs", macs) :
                new ObjectParameter("macs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_CTM", mapmParameter, macsParameter);
        }
    
        public virtual int Delete_CTN(string maPN)
        {
            var maPNParameter = maPN != null ?
                new ObjectParameter("MaPN", maPN) :
                new ObjectParameter("MaPN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_CTN", maPNParameter);
        }
    
        public virtual int Delete_DG(string madg)
        {
            var madgParameter = madg != null ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_DG", madgParameter);
        }
    
        public virtual int Delete_KeSach(string make)
        {
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_KeSach", makeParameter);
        }
    
        public virtual int Delete_NCC(string mancc)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_NCC", manccParameter);
        }
    
        public virtual int Delete_NXB(string manxb)
        {
            var manxbParameter = manxb != null ?
                new ObjectParameter("manxb", manxb) :
                new ObjectParameter("manxb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_NXB", manxbParameter);
        }
    
        public virtual int Delete_PM(string mapm)
        {
            var mapmParameter = mapm != null ?
                new ObjectParameter("mapm", mapm) :
                new ObjectParameter("mapm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_PM", mapmParameter);
        }
    
        public virtual int Delete_PN(string maPN)
        {
            var maPNParameter = maPN != null ?
                new ObjectParameter("MaPN", maPN) :
                new ObjectParameter("MaPN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_PN", maPNParameter);
        }
    
        public virtual int Delete_TG(string matg)
        {
            var matgParameter = matg != null ?
                new ObjectParameter("matg", matg) :
                new ObjectParameter("matg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_TG", matgParameter);
        }
    
        public virtual int Delete_TS(string mats)
        {
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_TS", matsParameter);
        }
    
        public virtual int Delete_TT(string matt)
        {
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_TT", mattParameter);
        }
    
        public virtual int Delete_V(string mats, string matg)
        {
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var matgParameter = matg != null ?
                new ObjectParameter("matg", matg) :
                new ObjectParameter("matg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_V", matsParameter, matgParameter);
        }
    
        public virtual int Get_TS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Get_TS");
        }
    
        public virtual int Insert_CS(string macs, string mats)
        {
            var macsParameter = macs != null ?
                new ObjectParameter("macs", macs) :
                new ObjectParameter("macs", typeof(string));
    
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_CS", macsParameter, matsParameter);
        }
    
        public virtual int Insert_CTM(string mapm, string macs, string tinhtrang)
        {
            var mapmParameter = mapm != null ?
                new ObjectParameter("mapm", mapm) :
                new ObjectParameter("mapm", typeof(string));
    
            var macsParameter = macs != null ?
                new ObjectParameter("macs", macs) :
                new ObjectParameter("macs", typeof(string));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_CTM", mapmParameter, macsParameter, tinhtrangParameter);
        }
    
        public virtual int Insert_CTN(string mapn, string mats, Nullable<int> soluong, Nullable<int> dongia)
        {
            var mapnParameter = mapn != null ?
                new ObjectParameter("mapn", mapn) :
                new ObjectParameter("mapn", typeof(string));
    
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_CTN", mapnParameter, matsParameter, soluongParameter, dongiaParameter);
        }
    
        public virtual int Insert_DG(string madg, string iddg, string tendg, string gioitinhdg, Nullable<System.DateTime> ngaysinhdg, string diachidg, string sdtdg)
        {
            var madgParameter = madg != null ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(string));
    
            var iddgParameter = iddg != null ?
                new ObjectParameter("iddg", iddg) :
                new ObjectParameter("iddg", typeof(string));
    
            var tendgParameter = tendg != null ?
                new ObjectParameter("tendg", tendg) :
                new ObjectParameter("tendg", typeof(string));
    
            var gioitinhdgParameter = gioitinhdg != null ?
                new ObjectParameter("gioitinhdg", gioitinhdg) :
                new ObjectParameter("gioitinhdg", typeof(string));
    
            var ngaysinhdgParameter = ngaysinhdg.HasValue ?
                new ObjectParameter("ngaysinhdg", ngaysinhdg) :
                new ObjectParameter("ngaysinhdg", typeof(System.DateTime));
    
            var diachidgParameter = diachidg != null ?
                new ObjectParameter("diachidg", diachidg) :
                new ObjectParameter("diachidg", typeof(string));
    
            var sdtdgParameter = sdtdg != null ?
                new ObjectParameter("sdtdg", sdtdg) :
                new ObjectParameter("sdtdg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_DG", madgParameter, iddgParameter, tendgParameter, gioitinhdgParameter, ngaysinhdgParameter, diachidgParameter, sdtdgParameter);
        }
    
        public virtual int Insert_KeSach(string make, string chatlieu, Nullable<int> succhua)
        {
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            var chatlieuParameter = chatlieu != null ?
                new ObjectParameter("chatlieu", chatlieu) :
                new ObjectParameter("chatlieu", typeof(string));
    
            var succhuaParameter = succhua.HasValue ?
                new ObjectParameter("succhua", succhua) :
                new ObjectParameter("succhua", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_KeSach", makeParameter, chatlieuParameter, succhuaParameter);
        }
    
        public virtual int Insert_NCC(string mancc, string tenncc, string diachincc, string sdtncc, string email)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            var diachinccParameter = diachincc != null ?
                new ObjectParameter("diachincc", diachincc) :
                new ObjectParameter("diachincc", typeof(string));
    
            var sdtnccParameter = sdtncc != null ?
                new ObjectParameter("sdtncc", sdtncc) :
                new ObjectParameter("sdtncc", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_NCC", manccParameter, tennccParameter, diachinccParameter, sdtnccParameter, emailParameter);
        }
    
        public virtual int Insert_NXB(string manxb, string tennxb, string diachinxb, string sdtnxb, string emailnxb)
        {
            var manxbParameter = manxb != null ?
                new ObjectParameter("manxb", manxb) :
                new ObjectParameter("manxb", typeof(string));
    
            var tennxbParameter = tennxb != null ?
                new ObjectParameter("tennxb", tennxb) :
                new ObjectParameter("tennxb", typeof(string));
    
            var diachinxbParameter = diachinxb != null ?
                new ObjectParameter("diachinxb", diachinxb) :
                new ObjectParameter("diachinxb", typeof(string));
    
            var sdtnxbParameter = sdtnxb != null ?
                new ObjectParameter("sdtnxb", sdtnxb) :
                new ObjectParameter("sdtnxb", typeof(string));
    
            var emailnxbParameter = emailnxb != null ?
                new ObjectParameter("emailnxb", emailnxb) :
                new ObjectParameter("emailnxb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_NXB", manxbParameter, tennxbParameter, diachinxbParameter, sdtnxbParameter, emailnxbParameter);
        }
    
        public virtual int Insert_PhieuMuon(string mapm, Nullable<System.DateTime> ngaymuon, Nullable<System.DateTime> ngaytra, string madg, string matt, string macs, string tinhtrang)
        {
            var mapmParameter = mapm != null ?
                new ObjectParameter("mapm", mapm) :
                new ObjectParameter("mapm", typeof(string));
    
            var ngaymuonParameter = ngaymuon.HasValue ?
                new ObjectParameter("ngaymuon", ngaymuon) :
                new ObjectParameter("ngaymuon", typeof(System.DateTime));
    
            var ngaytraParameter = ngaytra.HasValue ?
                new ObjectParameter("ngaytra", ngaytra) :
                new ObjectParameter("ngaytra", typeof(System.DateTime));
    
            var madgParameter = madg != null ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(string));
    
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            var macsParameter = macs != null ?
                new ObjectParameter("macs", macs) :
                new ObjectParameter("macs", typeof(string));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PhieuMuon", mapmParameter, ngaymuonParameter, ngaytraParameter, madgParameter, mattParameter, macsParameter, tinhtrangParameter);
        }
    
        public virtual int Insert_PhieuNhap(string mapn, Nullable<System.DateTime> ngaylap, string matt, string mancc, string mats, Nullable<int> soluong, Nullable<int> dongia)
        {
            var mapnParameter = mapn != null ?
                new ObjectParameter("mapn", mapn) :
                new ObjectParameter("mapn", typeof(string));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PhieuNhap", mapnParameter, ngaylapParameter, mattParameter, manccParameter, matsParameter, soluongParameter, dongiaParameter);
        }
    
        public virtual int Insert_PM(string mapm, Nullable<System.DateTime> ngaymuon, Nullable<System.DateTime> ngaytra, string madg, string matt)
        {
            var mapmParameter = mapm != null ?
                new ObjectParameter("mapm", mapm) :
                new ObjectParameter("mapm", typeof(string));
    
            var ngaymuonParameter = ngaymuon.HasValue ?
                new ObjectParameter("ngaymuon", ngaymuon) :
                new ObjectParameter("ngaymuon", typeof(System.DateTime));
    
            var ngaytraParameter = ngaytra.HasValue ?
                new ObjectParameter("ngaytra", ngaytra) :
                new ObjectParameter("ngaytra", typeof(System.DateTime));
    
            var madgParameter = madg != null ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(string));
    
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PM", mapmParameter, ngaymuonParameter, ngaytraParameter, madgParameter, mattParameter);
        }
    
        public virtual int Insert_PN(string mapn, Nullable<System.DateTime> ngaylap, string matt, string mancc)
        {
            var mapnParameter = mapn != null ?
                new ObjectParameter("mapn", mapn) :
                new ObjectParameter("mapn", typeof(string));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PN", mapnParameter, ngaylapParameter, mattParameter, manccParameter);
        }
    
        public virtual int Insert_TG(string matg, string tentg, string gioitinhtg, Nullable<System.DateTime> ngaysinhtg, string quequantg)
        {
            var matgParameter = matg != null ?
                new ObjectParameter("matg", matg) :
                new ObjectParameter("matg", typeof(string));
    
            var tentgParameter = tentg != null ?
                new ObjectParameter("tentg", tentg) :
                new ObjectParameter("tentg", typeof(string));
    
            var gioitinhtgParameter = gioitinhtg != null ?
                new ObjectParameter("gioitinhtg", gioitinhtg) :
                new ObjectParameter("gioitinhtg", typeof(string));
    
            var ngaysinhtgParameter = ngaysinhtg.HasValue ?
                new ObjectParameter("ngaysinhtg", ngaysinhtg) :
                new ObjectParameter("ngaysinhtg", typeof(System.DateTime));
    
            var quequantgParameter = quequantg != null ?
                new ObjectParameter("quequantg", quequantg) :
                new ObjectParameter("quequantg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_TG", matgParameter, tentgParameter, gioitinhtgParameter, ngaysinhtgParameter, quequantgParameter);
        }
    
        public virtual int Insert_TS(string mats, string tents, Nullable<int> namxb, string theloai, string manxb, string make, Nullable<int> soluong)
        {
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var tentsParameter = tents != null ?
                new ObjectParameter("tents", tents) :
                new ObjectParameter("tents", typeof(string));
    
            var namxbParameter = namxb.HasValue ?
                new ObjectParameter("namxb", namxb) :
                new ObjectParameter("namxb", typeof(int));
    
            var theloaiParameter = theloai != null ?
                new ObjectParameter("theloai", theloai) :
                new ObjectParameter("theloai", typeof(string));
    
            var manxbParameter = manxb != null ?
                new ObjectParameter("manxb", manxb) :
                new ObjectParameter("manxb", typeof(string));
    
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_TS", matsParameter, tentsParameter, namxbParameter, theloaiParameter, manxbParameter, makeParameter, soluongParameter);
        }
    
        public virtual int Insert_TT(string matt, string tentt, string gioitinhtt, Nullable<System.DateTime> ngaysinhtt, string diachitt, string sdttt, string chucvu)
        {
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            var tenttParameter = tentt != null ?
                new ObjectParameter("tentt", tentt) :
                new ObjectParameter("tentt", typeof(string));
    
            var gioitinhttParameter = gioitinhtt != null ?
                new ObjectParameter("gioitinhtt", gioitinhtt) :
                new ObjectParameter("gioitinhtt", typeof(string));
    
            var ngaysinhttParameter = ngaysinhtt.HasValue ?
                new ObjectParameter("ngaysinhtt", ngaysinhtt) :
                new ObjectParameter("ngaysinhtt", typeof(System.DateTime));
    
            var diachittParameter = diachitt != null ?
                new ObjectParameter("diachitt", diachitt) :
                new ObjectParameter("diachitt", typeof(string));
    
            var sdtttParameter = sdttt != null ?
                new ObjectParameter("sdttt", sdttt) :
                new ObjectParameter("sdttt", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("Chucvu", chucvu) :
                new ObjectParameter("Chucvu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_TT", mattParameter, tenttParameter, gioitinhttParameter, ngaysinhttParameter, diachittParameter, sdtttParameter, chucvuParameter);
        }
    
        public virtual int Insert_V(string mats, string matg, Nullable<int> sotrang)
        {
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var matgParameter = matg != null ?
                new ObjectParameter("matg", matg) :
                new ObjectParameter("matg", typeof(string));
    
            var sotrangParameter = sotrang.HasValue ?
                new ObjectParameter("sotrang", sotrang) :
                new ObjectParameter("sotrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_V", matsParameter, matgParameter, sotrangParameter);
        }
    
        public virtual ObjectResult<Select_CS_Result> Select_CS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_CS_Result>("Select_CS");
        }
    
        public virtual ObjectResult<Select_CTM_Result> Select_CTM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_CTM_Result>("Select_CTM");
        }
    
        public virtual ObjectResult<Select_CTN_Result> Select_CTN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_CTN_Result>("Select_CTN");
        }
    
        public virtual ObjectResult<Select_DG_Result> Select_DG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_DG_Result>("Select_DG");
        }
    
        public virtual ObjectResult<Select_KeSach_Result> Select_KeSach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_KeSach_Result>("Select_KeSach");
        }
    
        public virtual ObjectResult<Select_NCC_Result> Select_NCC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_NCC_Result>("Select_NCC");
        }
    
        public virtual ObjectResult<Select_NXB_Result> Select_NXB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_NXB_Result>("Select_NXB");
        }
    
        public virtual ObjectResult<Select_PM_Result> Select_PM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_PM_Result>("Select_PM");
        }
    
        public virtual ObjectResult<Select_PN_Result> Select_PN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_PN_Result>("Select_PN");
        }
    
        public virtual ObjectResult<Select_TG_Result> Select_TG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_TG_Result>("Select_TG");
        }
    
        public virtual ObjectResult<Select_TS_Result> Select_TS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_TS_Result>("Select_TS");
        }
    
        public virtual ObjectResult<Select_TT_Result> Select_TT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_TT_Result>("Select_TT");
        }
    
        public virtual ObjectResult<Select_V_Result> Select_V()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_V_Result>("Select_V");
        }
    
        public virtual int Them_TS_V(string mats, string tents, Nullable<int> namxb, string theloai, string manxb, string make, Nullable<int> soluong, string matg, Nullable<int> sotrang)
        {
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var tentsParameter = tents != null ?
                new ObjectParameter("tents", tents) :
                new ObjectParameter("tents", typeof(string));
    
            var namxbParameter = namxb.HasValue ?
                new ObjectParameter("namxb", namxb) :
                new ObjectParameter("namxb", typeof(int));
    
            var theloaiParameter = theloai != null ?
                new ObjectParameter("theloai", theloai) :
                new ObjectParameter("theloai", typeof(string));
    
            var manxbParameter = manxb != null ?
                new ObjectParameter("manxb", manxb) :
                new ObjectParameter("manxb", typeof(string));
    
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var matgParameter = matg != null ?
                new ObjectParameter("matg", matg) :
                new ObjectParameter("matg", typeof(string));
    
            var sotrangParameter = sotrang.HasValue ?
                new ObjectParameter("sotrang", sotrang) :
                new ObjectParameter("sotrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Them_TS_V", matsParameter, tentsParameter, namxbParameter, theloaiParameter, manxbParameter, makeParameter, soluongParameter, matgParameter, sotrangParameter);
        }
    
        public virtual ObjectResult<string> ThongKe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ThongKe");
        }
    
        public virtual int Update_CTM(string mapm, string macs, string tinhtrang)
        {
            var mapmParameter = mapm != null ?
                new ObjectParameter("mapm", mapm) :
                new ObjectParameter("mapm", typeof(string));
    
            var macsParameter = macs != null ?
                new ObjectParameter("macs", macs) :
                new ObjectParameter("macs", typeof(string));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_CTM", mapmParameter, macsParameter, tinhtrangParameter);
        }
    
        public virtual int Update_CTN(string mapn, string mats, Nullable<int> soluong, Nullable<decimal> dongia)
        {
            var mapnParameter = mapn != null ?
                new ObjectParameter("mapn", mapn) :
                new ObjectParameter("mapn", typeof(string));
    
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_CTN", mapnParameter, matsParameter, soluongParameter, dongiaParameter);
        }
    
        public virtual int Update_DG(string madg, string iddg, string tendg, string gioitinhdg, Nullable<System.DateTime> ngaysinhdg, string diachidg, string sdtdg)
        {
            var madgParameter = madg != null ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(string));
    
            var iddgParameter = iddg != null ?
                new ObjectParameter("iddg", iddg) :
                new ObjectParameter("iddg", typeof(string));
    
            var tendgParameter = tendg != null ?
                new ObjectParameter("tendg", tendg) :
                new ObjectParameter("tendg", typeof(string));
    
            var gioitinhdgParameter = gioitinhdg != null ?
                new ObjectParameter("gioitinhdg", gioitinhdg) :
                new ObjectParameter("gioitinhdg", typeof(string));
    
            var ngaysinhdgParameter = ngaysinhdg.HasValue ?
                new ObjectParameter("ngaysinhdg", ngaysinhdg) :
                new ObjectParameter("ngaysinhdg", typeof(System.DateTime));
    
            var diachidgParameter = diachidg != null ?
                new ObjectParameter("diachidg", diachidg) :
                new ObjectParameter("diachidg", typeof(string));
    
            var sdtdgParameter = sdtdg != null ?
                new ObjectParameter("sdtdg", sdtdg) :
                new ObjectParameter("sdtdg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_DG", madgParameter, iddgParameter, tendgParameter, gioitinhdgParameter, ngaysinhdgParameter, diachidgParameter, sdtdgParameter);
        }
    
        public virtual int Update_KeSach(string make, string chatlieu, Nullable<int> succhua)
        {
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            var chatlieuParameter = chatlieu != null ?
                new ObjectParameter("chatlieu", chatlieu) :
                new ObjectParameter("chatlieu", typeof(string));
    
            var succhuaParameter = succhua.HasValue ?
                new ObjectParameter("succhua", succhua) :
                new ObjectParameter("succhua", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_KeSach", makeParameter, chatlieuParameter, succhuaParameter);
        }
    
        public virtual int Update_NCC(string mancc, string tenncc, string diachincc, string sdtncc, string email)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            var diachinccParameter = diachincc != null ?
                new ObjectParameter("diachincc", diachincc) :
                new ObjectParameter("diachincc", typeof(string));
    
            var sdtnccParameter = sdtncc != null ?
                new ObjectParameter("sdtncc", sdtncc) :
                new ObjectParameter("sdtncc", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_NCC", manccParameter, tennccParameter, diachinccParameter, sdtnccParameter, emailParameter);
        }
    
        public virtual int Update_NXB(string manxb, string tennxb, string diachinxb, string sdtnxb, string emailnxb)
        {
            var manxbParameter = manxb != null ?
                new ObjectParameter("manxb", manxb) :
                new ObjectParameter("manxb", typeof(string));
    
            var tennxbParameter = tennxb != null ?
                new ObjectParameter("tennxb", tennxb) :
                new ObjectParameter("tennxb", typeof(string));
    
            var diachinxbParameter = diachinxb != null ?
                new ObjectParameter("diachinxb", diachinxb) :
                new ObjectParameter("diachinxb", typeof(string));
    
            var sdtnxbParameter = sdtnxb != null ?
                new ObjectParameter("sdtnxb", sdtnxb) :
                new ObjectParameter("sdtnxb", typeof(string));
    
            var emailnxbParameter = emailnxb != null ?
                new ObjectParameter("emailnxb", emailnxb) :
                new ObjectParameter("emailnxb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_NXB", manxbParameter, tennxbParameter, diachinxbParameter, sdtnxbParameter, emailnxbParameter);
        }
    
        public virtual int Update_PhieuMuon(string mapm, Nullable<System.DateTime> ngaymuon, Nullable<System.DateTime> ngaytra, string madg, string matt, string macs, string tinhtrang)
        {
            var mapmParameter = mapm != null ?
                new ObjectParameter("mapm", mapm) :
                new ObjectParameter("mapm", typeof(string));
    
            var ngaymuonParameter = ngaymuon.HasValue ?
                new ObjectParameter("ngaymuon", ngaymuon) :
                new ObjectParameter("ngaymuon", typeof(System.DateTime));
    
            var ngaytraParameter = ngaytra.HasValue ?
                new ObjectParameter("ngaytra", ngaytra) :
                new ObjectParameter("ngaytra", typeof(System.DateTime));
    
            var madgParameter = madg != null ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(string));
    
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            var macsParameter = macs != null ?
                new ObjectParameter("macs", macs) :
                new ObjectParameter("macs", typeof(string));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_PhieuMuon", mapmParameter, ngaymuonParameter, ngaytraParameter, madgParameter, mattParameter, macsParameter, tinhtrangParameter);
        }
    
        public virtual int Update_PhieuNhap(string mapn, Nullable<System.DateTime> ngaylap, string matt, string mancc, string mats, Nullable<int> soluong, Nullable<int> dongia)
        {
            var mapnParameter = mapn != null ?
                new ObjectParameter("mapn", mapn) :
                new ObjectParameter("mapn", typeof(string));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_PhieuNhap", mapnParameter, ngaylapParameter, mattParameter, manccParameter, matsParameter, soluongParameter, dongiaParameter);
        }
    
        public virtual int Update_PM(string mapm, Nullable<System.DateTime> ngaymuon, Nullable<System.DateTime> ngaytra, string madg, string matt)
        {
            var mapmParameter = mapm != null ?
                new ObjectParameter("mapm", mapm) :
                new ObjectParameter("mapm", typeof(string));
    
            var ngaymuonParameter = ngaymuon.HasValue ?
                new ObjectParameter("ngaymuon", ngaymuon) :
                new ObjectParameter("ngaymuon", typeof(System.DateTime));
    
            var ngaytraParameter = ngaytra.HasValue ?
                new ObjectParameter("ngaytra", ngaytra) :
                new ObjectParameter("ngaytra", typeof(System.DateTime));
    
            var madgParameter = madg != null ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(string));
    
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_PM", mapmParameter, ngaymuonParameter, ngaytraParameter, madgParameter, mattParameter);
        }
    
        public virtual int Update_PN(string maPN, Nullable<System.DateTime> ngaylap, string matt, string mancc)
        {
            var maPNParameter = maPN != null ?
                new ObjectParameter("MaPN", maPN) :
                new ObjectParameter("MaPN", typeof(string));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_PN", maPNParameter, ngaylapParameter, mattParameter, manccParameter);
        }
    
        public virtual int Update_TG(string matg, string tentg, string gioitinhtg, Nullable<System.DateTime> ngaysinhtg, string quequantg)
        {
            var matgParameter = matg != null ?
                new ObjectParameter("matg", matg) :
                new ObjectParameter("matg", typeof(string));
    
            var tentgParameter = tentg != null ?
                new ObjectParameter("tentg", tentg) :
                new ObjectParameter("tentg", typeof(string));
    
            var gioitinhtgParameter = gioitinhtg != null ?
                new ObjectParameter("gioitinhtg", gioitinhtg) :
                new ObjectParameter("gioitinhtg", typeof(string));
    
            var ngaysinhtgParameter = ngaysinhtg.HasValue ?
                new ObjectParameter("ngaysinhtg", ngaysinhtg) :
                new ObjectParameter("ngaysinhtg", typeof(System.DateTime));
    
            var quequantgParameter = quequantg != null ?
                new ObjectParameter("quequantg", quequantg) :
                new ObjectParameter("quequantg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_TG", matgParameter, tentgParameter, gioitinhtgParameter, ngaysinhtgParameter, quequantgParameter);
        }
    
        public virtual int Update_TS(string mats, string tents, Nullable<int> namxb, string theloai, string manxb, string make, Nullable<int> soluong)
        {
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var tentsParameter = tents != null ?
                new ObjectParameter("tents", tents) :
                new ObjectParameter("tents", typeof(string));
    
            var namxbParameter = namxb.HasValue ?
                new ObjectParameter("namxb", namxb) :
                new ObjectParameter("namxb", typeof(int));
    
            var theloaiParameter = theloai != null ?
                new ObjectParameter("theloai", theloai) :
                new ObjectParameter("theloai", typeof(string));
    
            var manxbParameter = manxb != null ?
                new ObjectParameter("manxb", manxb) :
                new ObjectParameter("manxb", typeof(string));
    
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_TS", matsParameter, tentsParameter, namxbParameter, theloaiParameter, manxbParameter, makeParameter, soluongParameter);
        }
    
        public virtual int Update_TT(string matt, string tentt, string gioitinhtt, Nullable<System.DateTime> ngaysinhtt, string diachitt, string sdttt, string chucvu)
        {
            var mattParameter = matt != null ?
                new ObjectParameter("matt", matt) :
                new ObjectParameter("matt", typeof(string));
    
            var tenttParameter = tentt != null ?
                new ObjectParameter("tentt", tentt) :
                new ObjectParameter("tentt", typeof(string));
    
            var gioitinhttParameter = gioitinhtt != null ?
                new ObjectParameter("gioitinhtt", gioitinhtt) :
                new ObjectParameter("gioitinhtt", typeof(string));
    
            var ngaysinhttParameter = ngaysinhtt.HasValue ?
                new ObjectParameter("ngaysinhtt", ngaysinhtt) :
                new ObjectParameter("ngaysinhtt", typeof(System.DateTime));
    
            var diachittParameter = diachitt != null ?
                new ObjectParameter("diachitt", diachitt) :
                new ObjectParameter("diachitt", typeof(string));
    
            var sdtttParameter = sdttt != null ?
                new ObjectParameter("sdttt", sdttt) :
                new ObjectParameter("sdttt", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("Chucvu", chucvu) :
                new ObjectParameter("Chucvu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_TT", mattParameter, tenttParameter, gioitinhttParameter, ngaysinhttParameter, diachittParameter, sdtttParameter, chucvuParameter);
        }
    
        public virtual int Update_V(string mats, string matg, Nullable<int> sotrang)
        {
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            var matgParameter = matg != null ?
                new ObjectParameter("matg", matg) :
                new ObjectParameter("matg", typeof(string));
    
            var sotrangParameter = sotrang.HasValue ?
                new ObjectParameter("sotrang", sotrang) :
                new ObjectParameter("sotrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_V", matsParameter, matgParameter, sotrangParameter);
        }
    
        public virtual int Xoa_TS_V(string macs, string mats)
        {
            var macsParameter = macs != null ?
                new ObjectParameter("macs", macs) :
                new ObjectParameter("macs", typeof(string));
    
            var matsParameter = mats != null ?
                new ObjectParameter("mats", mats) :
                new ObjectParameter("mats", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Xoa_TS_V", macsParameter, matsParameter);
        }
    
        public virtual int Delete_Nguoidung(string maNguoiDung)
        {
            var maNguoiDungParameter = maNguoiDung != null ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Nguoidung", maNguoiDungParameter);
        }
    
        public virtual int Insert_Nguoidung(string maNguoiDung, string maTT, string matKhau)
        {
            var maNguoiDungParameter = maNguoiDung != null ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(string));
    
            var maTTParameter = maTT != null ?
                new ObjectParameter("MaTT", maTT) :
                new ObjectParameter("MaTT", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Nguoidung", maNguoiDungParameter, maTTParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<Select_Nguoidung_Result> Select_Nguoidung()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Nguoidung_Result>("Select_Nguoidung");
        }
    
        public virtual int Update_Nguoidung(string maNguoiDung, string maTT, string matKhau)
        {
            var maNguoiDungParameter = maNguoiDung != null ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(string));
    
            var maTTParameter = maTT != null ?
                new ObjectParameter("MaTT", maTT) :
                new ObjectParameter("MaTT", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Nguoidung", maNguoiDungParameter, maTTParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<SelectPQ_Result> SelectPQ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPQ_Result>("SelectPQ");
        }
    
        public virtual ObjectResult<SelectQuyen_Result> SelectQuyen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectQuyen_Result>("SelectQuyen");
        }
    
        public virtual int Delete_PQ(string maQuyen, string maNguoiDung)
        {
            var maQuyenParameter = maQuyen != null ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(string));
    
            var maNguoiDungParameter = maNguoiDung != null ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_PQ", maQuyenParameter, maNguoiDungParameter);
        }
    
        public virtual int Delete_Quyen(string maQuyen)
        {
            var maQuyenParameter = maQuyen != null ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Quyen", maQuyenParameter);
        }
    
        public virtual ObjectResult<Select_PQ_Result> Select_PQ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_PQ_Result>("Select_PQ");
        }
    
        public virtual ObjectResult<Select_Quyen_Result> Select_Quyen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Quyen_Result>("Select_Quyen");
        }
    
        public virtual int Insert_Quyen(string maQuyen, Nullable<bool> xemSach, Nullable<bool> suaSach, Nullable<bool> xoaSach, Nullable<bool> themSach, Nullable<bool> themNguoiDung, Nullable<bool> xemNguoiDung, Nullable<bool> suaNguoiDung, Nullable<bool> xoaNguoiDung, Nullable<bool> xemMuonTra, Nullable<bool> themMuonTra, Nullable<bool> suaMuonTra, Nullable<bool> xoaMuonTra)
        {
            var maQuyenParameter = maQuyen != null ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(string));
    
            var xemSachParameter = xemSach.HasValue ?
                new ObjectParameter("XemSach", xemSach) :
                new ObjectParameter("XemSach", typeof(bool));
    
            var suaSachParameter = suaSach.HasValue ?
                new ObjectParameter("SuaSach", suaSach) :
                new ObjectParameter("SuaSach", typeof(bool));
    
            var xoaSachParameter = xoaSach.HasValue ?
                new ObjectParameter("XoaSach", xoaSach) :
                new ObjectParameter("XoaSach", typeof(bool));
    
            var themSachParameter = themSach.HasValue ?
                new ObjectParameter("ThemSach", themSach) :
                new ObjectParameter("ThemSach", typeof(bool));
    
            var themNguoiDungParameter = themNguoiDung.HasValue ?
                new ObjectParameter("ThemNguoiDung", themNguoiDung) :
                new ObjectParameter("ThemNguoiDung", typeof(bool));
    
            var xemNguoiDungParameter = xemNguoiDung.HasValue ?
                new ObjectParameter("XemNguoiDung", xemNguoiDung) :
                new ObjectParameter("XemNguoiDung", typeof(bool));
    
            var suaNguoiDungParameter = suaNguoiDung.HasValue ?
                new ObjectParameter("SuaNguoiDung", suaNguoiDung) :
                new ObjectParameter("SuaNguoiDung", typeof(bool));
    
            var xoaNguoiDungParameter = xoaNguoiDung.HasValue ?
                new ObjectParameter("XoaNguoiDung", xoaNguoiDung) :
                new ObjectParameter("XoaNguoiDung", typeof(bool));
    
            var xemMuonTraParameter = xemMuonTra.HasValue ?
                new ObjectParameter("XemMuonTra", xemMuonTra) :
                new ObjectParameter("XemMuonTra", typeof(bool));
    
            var themMuonTraParameter = themMuonTra.HasValue ?
                new ObjectParameter("ThemMuonTra", themMuonTra) :
                new ObjectParameter("ThemMuonTra", typeof(bool));
    
            var suaMuonTraParameter = suaMuonTra.HasValue ?
                new ObjectParameter("SuaMuonTra", suaMuonTra) :
                new ObjectParameter("SuaMuonTra", typeof(bool));
    
            var xoaMuonTraParameter = xoaMuonTra.HasValue ?
                new ObjectParameter("XoaMuonTra", xoaMuonTra) :
                new ObjectParameter("XoaMuonTra", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Quyen", maQuyenParameter, xemSachParameter, suaSachParameter, xoaSachParameter, themSachParameter, themNguoiDungParameter, xemNguoiDungParameter, suaNguoiDungParameter, xoaNguoiDungParameter, xemMuonTraParameter, themMuonTraParameter, suaMuonTraParameter, xoaMuonTraParameter);
        }
    
        public virtual int Insert_PhanQuyen(string maNguoiDung, string maQuyen)
        {
            var maNguoiDungParameter = maNguoiDung != null ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(string));
    
            var maQuyenParameter = maQuyen != null ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PhanQuyen", maNguoiDungParameter, maQuyenParameter);
        }
    
        public virtual ObjectResult<Get_PQ_Result> Get_PQ(string maNguoiDung)
        {
            var maNguoiDungParameter = maNguoiDung != null ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_PQ_Result>("Get_PQ", maNguoiDungParameter);
        }
    
        public virtual ObjectResult<Get_Quyen_Result> Get_Quyen(string maQuyen)
        {
            var maQuyenParameter = maQuyen != null ?
                new ObjectParameter("MaQuyen", maQuyen) :
                new ObjectParameter("MaQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Quyen_Result>("Get_Quyen", maQuyenParameter);
        }
    
        public virtual ObjectResult<Get_NguoiDung_Result> Get_NguoiDung(string maNguoiDung)
        {
            var maNguoiDungParameter = maNguoiDung != null ?
                new ObjectParameter("MaNguoiDung", maNguoiDung) :
                new ObjectParameter("MaNguoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_NguoiDung_Result>("Get_NguoiDung", maNguoiDungParameter);
        }
    
        public virtual ObjectResult<Get_ThuThu_Result> Get_ThuThu(string maThuThu)
        {
            var maThuThuParameter = maThuThu != null ?
                new ObjectParameter("MaThuThu", maThuThu) :
                new ObjectParameter("MaThuThu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ThuThu_Result>("Get_ThuThu", maThuThuParameter);
        }
    
        public virtual int Delete_GV(string maGV)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_GV", maGVParameter);
        }
    
        public virtual int Delete_SV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_SV", maSVParameter);
        }
    
        public virtual ObjectResult<Get_GV_Result> Get_GV(string maGV)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_GV_Result>("Get_GV", maGVParameter);
        }
    
        public virtual ObjectResult<Get_SV_Result> Get_SV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_SV_Result>("Get_SV", maSVParameter);
        }
    
        public virtual int Insert_GV(string maGV, string tenGV, string dienThoai, string diaChi, string maKhoa, Nullable<System.DateTime> ngaySinh, string gioiTinh)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("TenGV", tenGV) :
                new ObjectParameter("TenGV", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_GV", maGVParameter, tenGVParameter, dienThoaiParameter, diaChiParameter, maKhoaParameter, ngaySinhParameter, gioiTinhParameter);
        }
    
        public virtual int Insert_SV(string maSV, string tenSV, string maLop, string dienThoai, string diaChi, Nullable<System.DateTime> ngaySinh, string gioiTinh)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var tenSVParameter = tenSV != null ?
                new ObjectParameter("TenSV", tenSV) :
                new ObjectParameter("TenSV", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_SV", maSVParameter, tenSVParameter, maLopParameter, dienThoaiParameter, diaChiParameter, ngaySinhParameter, gioiTinhParameter);
        }
    
        public virtual ObjectResult<Select_GV_Result> Select_GV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_GV_Result>("Select_GV");
        }
    
        public virtual ObjectResult<Select_SV_Result> Select_SV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_SV_Result>("Select_SV");
        }
    
        public virtual int Update_GV(string maGV, string tenGV, string maKhoa, string sdtGV, string diachiGV, Nullable<System.DateTime> ngaysinhGV, string gioitinhGV)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(string));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("tenGV", tenGV) :
                new ObjectParameter("tenGV", typeof(string));
    
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(string));
    
            var sdtGVParameter = sdtGV != null ?
                new ObjectParameter("sdtGV", sdtGV) :
                new ObjectParameter("sdtGV", typeof(string));
    
            var diachiGVParameter = diachiGV != null ?
                new ObjectParameter("diachiGV", diachiGV) :
                new ObjectParameter("diachiGV", typeof(string));
    
            var ngaysinhGVParameter = ngaysinhGV.HasValue ?
                new ObjectParameter("ngaysinhGV", ngaysinhGV) :
                new ObjectParameter("ngaysinhGV", typeof(System.DateTime));
    
            var gioitinhGVParameter = gioitinhGV != null ?
                new ObjectParameter("gioitinhGV", gioitinhGV) :
                new ObjectParameter("gioitinhGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_GV", maGVParameter, tenGVParameter, maKhoaParameter, sdtGVParameter, diachiGVParameter, ngaysinhGVParameter, gioitinhGVParameter);
        }
    
        public virtual int Update_SV(string maSV, string tenSV, string maLop, string sdtSV, string diachiSV, Nullable<System.DateTime> ngaysinhSV, string gioitinhSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var tenSVParameter = tenSV != null ?
                new ObjectParameter("tenSV", tenSV) :
                new ObjectParameter("tenSV", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(string));
    
            var sdtSVParameter = sdtSV != null ?
                new ObjectParameter("sdtSV", sdtSV) :
                new ObjectParameter("sdtSV", typeof(string));
    
            var diachiSVParameter = diachiSV != null ?
                new ObjectParameter("diachiSV", diachiSV) :
                new ObjectParameter("diachiSV", typeof(string));
    
            var ngaysinhSVParameter = ngaysinhSV.HasValue ?
                new ObjectParameter("ngaysinhSV", ngaysinhSV) :
                new ObjectParameter("ngaysinhSV", typeof(System.DateTime));
    
            var gioitinhSVParameter = gioitinhSV != null ?
                new ObjectParameter("gioitinhSV", gioitinhSV) :
                new ObjectParameter("gioitinhSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_SV", maSVParameter, tenSVParameter, maLopParameter, sdtSVParameter, diachiSVParameter, ngaysinhSVParameter, gioitinhSVParameter);
        }
    
        public virtual int Delete_Khoa(string maKhoa)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Khoa", maKhoaParameter);
        }
    
        public virtual int Delete_Lop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Lop", maLopParameter);
        }
    
        public virtual int Insert_Khoa(string maKhoa, string tenKhoa)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(string));
    
            var tenKhoaParameter = tenKhoa != null ?
                new ObjectParameter("TenKhoa", tenKhoa) :
                new ObjectParameter("TenKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Khoa", maKhoaParameter, tenKhoaParameter);
        }
    
        public virtual int Insert_Lop(string maLop, string maKhoa)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Lop", maLopParameter, maKhoaParameter);
        }
    
        public virtual int Update_Khoa(string maKhoa, string tenKhoa)
        {
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(string));
    
            var tenKhoaParameter = tenKhoa != null ?
                new ObjectParameter("TenKhoa", tenKhoa) :
                new ObjectParameter("TenKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Khoa", maKhoaParameter, tenKhoaParameter);
        }
    
        public virtual int Update_Lop(string maLop, string maKhoa)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var maKhoaParameter = maKhoa != null ?
                new ObjectParameter("MaKhoa", maKhoa) :
                new ObjectParameter("MaKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Lop", maLopParameter, maKhoaParameter);
        }
    
        public virtual ObjectResult<DemSoLanDaMuon_Result> DemSoLanDaMuon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DemSoLanDaMuon_Result>("DemSoLanDaMuon");
        }
    }
}
