//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_WF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viet
    {
        public string MaTS { get; set; }
        public string MaTG { get; set; }
        public Nullable<int> SoTrang { get; set; }
    
        public virtual TacGia TacGia { get; set; }
        public virtual TuaSach TuaSach { get; set; }
    }
}
